# Generated by Django 3.0.4 on 2020-07-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Money',
            new_name='Addmoney',
        ),
    ]
