# Generated by Django 3.0.4 on 2020-07-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20200701_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmoney',
            name='returned',
        ),
    ]
