# Generated by Django 3.1.1 on 2021-01-04 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20201102_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='addmoney',
            name='status',
            field=models.CharField(choices=[('OA', 'Added'), ('OS', 'Given'), ('PS', 'Personal'), ('RET', 'Returned'), ('RETB', 'Bank Return')], default='PS', max_length=4),
        ),
    ]
