# Generated by Django 3.1.1 on 2021-01-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20210104_2259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='NotesEntry',
        ),
    ]
