# Generated by Django 3.0.8 on 2020-07-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarynote',
            name='sub',
        ),
        migrations.AlterField(
            model_name='diarynote',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
